- nt-app/src/updater.js
Add check if stored game path exists and use that instead of game path autodetection if so
Only execute powershell commands for game detection on win32 (needs testing!)
Add linux / steam deck game autodetection by polling likely steam install locations
> Updater improvements and linux game detection support

- nt-app/src/noita.js
environment variable "DEBUG_NO_LOCALHOST_CHECK" will allow connections from non-localhost NT mod clients. only for testing in weird container environments :)
> add env variable to skip localhost connection check

- noita_mod/core/files/scripts/utils.lua
- noita_mod/core/init.lua
Adds `polymorphable_NOT` tag to player when spawned, then removes it when run starts.
Will do nothing if  player already has `polymorphable_NOT` for some reason or another.
This prevents players from polymorphing by drinking polymorphine (it's still drinkable) and moving around before the run is started.
> Prevent polymorphing before run start

- nt-app/src/background.js
- nt-app/src/cmdLineArgs.js
- nt-app/src/noita.js
- nt-app/src/views/Update.vue
Adds a cmdLineArgs class with app-specific command line arguments
'--nt-noupdate' skips updater step, use at own risk
'--nt-offline' not implemented, for connecting to backend w/o twitch auth
'--nt-allow-remote-noita' replaces .env variable DEBUG_NO_LOCALHOST_CHECK
> Add command line arguments handling

- noita_mod/core/files/scripts/spell_eater.lua
Fixed an issue where banking a wand with always-casts would erroneously add that many slots to the wand.
This happened because the `deck_capacity` value includes the number of always casts, while the serialized value is intended to be the real wand capacity. Therefore deserialization would produce a wand with extra slots, *before* adding the always casts. This also affected display of the wand in the bank.
> Fix banked wands with always casts gaining slots

- noita_mod/core/files/scripts/remove_flags.lua
- nt-app/src/noita.js
Add a GameFlagRun "NT_is_host" when player is the lobby host. Can be seen by other noita mods and used for special integration such as theoretical synced TI. Maybe useful for host-only ingame NT core features?
Resolves #36
> Add NT_is_host run flag when you are the lobby host

- noita_mod/core/files/store.lua
- noita_mod/core/files/ws/events.lua
- noita_mod/core/files/ws/ws.lua
- noita_mod/core/init.lua
Move the ws.lua init into OnWorldInitialized - sometimes the async loop doesnt start and this makes it more consistent.
Also adds some health check variables for the ws async loop and player position updates that can be used elsewhere
> Tweak ws asyncloop

- noita_mod/core/files/scripts/ui.lua
Here is a first pass at showing spell charges in the bank. Caveats:
The font isn't the same as that used for displaying charges on spell cards. For spells, this isn't that big of a deal.
However, the current tooltip for wands renders the spell icons smaller, so the font is a bit too large. This is compounded with the font used being larger than the normal spell card font. As it stands, putting the charges above the spells is readable, albeit not too visually nice, so it could use improvement.
Addresses #30
> First-pass spells charge display in bank

- noita_mod/core/init.lua
- noita_mod/core/settings.lua
Implements #80 
The option defaults to OFF (progress will still be enabled by default) - Should gather some community feedback as to if we want to default this to ON?
> Add option to disable perk/spell/enemy progress in NT

- CHANGELOG.md
- noita_mod/core/files/append/heart_append.lua
- noita_mod/core/files/append/heart_better_append.lua
- noita_mod/core/files/scripts/utils.lua
- noita_mod/core/files/translations/translations.csv
- noita_mod/core/init.lua
Update extra max HP and better max HP pickups to no longer cause infinite health on client sync issues (does not fix the bug, but logs when it breaks, and gives the user the min HP from the heart)
> Extra max HP fixes

- noita_mod/core/files/scripts/util/player_ghosts.lua
- noita_mod/core/files/scripts/utils.lua
- noita_mod/core/files/ws/events.lua
Some (WIP) improvements to player ghost cosmetics (crown, amulet, more to come?) and other player ghost tracking
- Moving player ghost related code from utils.lua to a separate utils/player_ghosts.lua. This gets included by utils.lua, so shouldn't change much in itself.
- Caching player's player-ghost entity id in the player's entry in the PlayerList table. This allows quick access to the ghost entity without having to iterate over all (up to 90!) ghost entities every time we do something
- Storing the player-ghost cosmetic flags in the same PlayerList table entry. This allows player-ghosts to get their crowns and amulets back when you hide and re-show ghosts. Fixes #82
- Wands no longer disappear when hiding and re-showing ghosts either
~~Need to periodically (and/or on change/request) …
> Player ghost cosmetics fixes, refactoring

- noita_mod/core/files/scripts/hourglass_events.lua
This brings a little-used secret hourglass effect more in line with the others having 2 minute durations.
> Raise secret hourglass acceleratium time to 2 min

- noita_mod/core/files/ws/events.lua
player_ghosts.lua was being dofile-included more than once (in utils.lua and events.lua) - this happened to clobber appended replacements by noita emotes. While the emotes mod shouldn't outright replace our functions if possible, the workaround wasn't working anymore either.
Long story short, removing this dofile makes noita emotes work again with the recent player ghost fixes in #86 . oops.
> Fix noita emotes broken by extra / out of place dofile

- noita_mod/core/files/store.lua
This was causing (among other things perhaps?) the hourglass trigger appends to not work after a mod restart, because NT.HealthCheck could not be set to an empty table at init (global store not yet ready?), which the next line then attempts to access and fails, throwing a lua error.
> Fix NT.HealthCheck table access in sometimes illegal way

- noita_mod/core/files/entities/death_cam.xml
Fixes some illegal xml syntax in the entity definition for the "death_cam" (the message that pops up when you die and will respawn).
This does slightly adjust the scaling of the message but its insignificant and if anything, looks more proper.
> Fix xml error in death/respawn message

- noita_mod/core/settings.lua
Conga noticed a discrepancy in my emote keybind settings, I mistakenly refer to mouse_codes for evaluating both mouse and joystick inputs. Should be joystick_codes for joystick inputs!
> fix settings typo confusing mouse codes for joystick codes

- package.json
- yarn.lock
NOTE: when preparing the release, be sure to update the @noita-together/nt-message dependency; if you have the old version present from a previous build, it will not include the fix!
The frame encoder will no longer throw an error when receiving scale_x/scale_y values that aren't +-1, which was happening with the shrinking mage in the new enemies mod. Now, the encoder will encode a value such as -0.89 as -1. This means that other players won't see the scale change, but the NT app will not crash/fail on encoding the message.
I don't expect that adding this support is going to add a lot of value, so I don't have plans to build it, but if we learn of some demand we can go further.
> Bump nt-message for https://github.com/Noita-Together/nt-message/pull/1

- noita_mod/core/files/scripts/utils.lua
- noita_mod/core/files/translations/translations.csv
Update the ingame "$0 found an orb of knowledge" messages to also show which orb (by location). Additionally shows "east" or "west" for parallel world orbs.
Some locations don't have ingame translations, so adds (english only) translation keys for those
> Add the location of the orb to the '$0 found an orb' message ingame

- noita_mod/core/files/scripts/utils.lua
- noita_mod/core/init.lua
Uses ItemComponent to disable drinking the starting flask before the run begins
Then re-enables it after the run is started by the host
This prevents chugging bad potions safely during run setup 😄
Left in the polymorph immunity part for now too, it doesn't hurt I guess.
> Disable drinking the starting flask during pre-run stage

- noita_mod/core/files/scripts/utils.lua
require(...) isn't in noita's api, and it seems we can use bitop just fine without doing that. Trying broke stuff during testing!
> dont require bitop library, that doesnt work in noita smh

- nt-web-app/package.json
- nt-web-app/pages/api/auth/refresh.ts
- nt-web-app/utils/TwitchUtils.ts
- nt-web-app/utils/jwtUtils.ts
- yarn.lock
add environment variables to adjust it server side without pushing new code
> Extend access token and refresh token timeouts

- nt-app/src/views/Room.vue
wrapped chat messages in a child div and put zalgo fix of `overflow-y: hidden` on that child to prevent messages from shrinking in on themselves and the whole chat losing its scroll bar.
aka back to how chat behaved pre-electron update.
> fix chat scroll/sizing bug
